name = "PlutoExtractors"
uuid = "25cc9095-8c7a-4c84-8905-c5de52e7766c"
authors = ["ederag <edera@gmx.fr> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoTest = "cb4044da-4d16-4ffa-a6a3-8cad7f73ebdc"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
BenchmarkTools = "1"
MacroTools = "0.5"
Pluto = "0.19"
PlutoTest = "0.2"
Revise = "3"
julia = "1.6"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Revise", "LinearAlgebra"]
